
env_args:
    # env: 'TicTacToe'
    #env: 'Geister'
    env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.9
    forward_steps: 64
    compress_steps: 4
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.1
    update_episodes: 500
    batch_size: 48
    minimum_episodes: 10000
    maximum_episodes: 1000000
    epochs: -1
    num_batchers: 1
    eval_rate: 0.1
    worker:
        num_parallel: 8
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    seed: 440
    restart_epoch: 0

worker_args:
    server_address: '127.0.0.1'
    num_parallel: 8
