
env_args:
    # env: 'TicTacToe'
    #env: 'Geister'
    env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.8
    forward_steps: 12
    compress_steps: 4
    entropy_regularization: 0  # 1.0e-3
    entropy_regularization_decay: 0.1
    update_episodes: 1000
    batch_size: 300
    minimum_episodes: 20000
    maximum_episodes: 500000
    epochs: -1
    num_batchers: 8
    eval_rate: 0.1
    worker:
        num_parallel: 6
    lambda: 0.7
    policy_target: 'UPGO' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'UPGO' # 'VTRACE' 'TD' 'MC'
    seed: 440
    restart_epoch: 1

worker_args:
    server_address: '127.0.0.1'
    num_parallel: 8
