
env_args:
    # env: 'TicTacToe'
    # source: 'handyrl.envs.tictactoe'
    # env: 'Geister'
    # source: 'handyrl.envs.geister'
    env: 'HungryGeese'
    source: 'handyrl.envs.kaggle.hungry_geese'


train_args:
    turn_based_training: False
    observation: False
    gamma: 0.9
    forward_steps: 64
    compress_steps: 4
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.3
    update_episodes: 500
    batch_size: 500
    minimum_episodes: 10000
    maximum_episodes: 500000
    num_batchers: 8
    eval_rate: 0.1
    worker:
        num_parallel: 6
    lambda: 0.8
    policy_target: 'UPGO' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'VTRACE' # 'VTRACE' 'TD' 'MC'
    seed: 442
    restart_epoch: 550


worker_args:
    server_address: '127.0.0.1'
    num_parallel: 6

