
name: pytest

on:
  pull_request:
  push:

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r handyrl/envs/kaggle/requirements.txt
      - name: pytest
        run: |
          python -m pytest tests
